language: java
jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7
  - openjdk6
script: 
  - cd 'Build solutions/Traditional batch commands/'
  - bash buildSoftware.bash.sh
after_script:
# Wait until https://github.com/travis-ci/travis-ci/issues/1376 is fixed
#  - cd 'Packaged software/'
#  - java -jar "Java 程式設計世界哈囉！(Hello Java world!).jar"
  - cd 'Built software'
  - java Main_program
