language: java
jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7
  - openjdk6
script: 
  - cd 'Build solutions/Traditional batch commands/'
  - bash buildSoftware.bash.sh
after_script:
  - cd 'Built software'
  - java Main_program
